name: Mineral

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  fishing:
    runs-on: ubuntu-latest
    concurrency:
      group: mineral

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'LalatinaHub/Mineral'
          token: ${{ secrets.GIT_TOKEN }}
      - name: Get secrets
        run: |
          echo ${{ secrets.BOT_TOKEN }} > ./session
          echo ${{ secrets.API_ID }} > ./api_id
          echo ${{ secrets.API_HASH }} > ./api_hash
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Start Mineral
        run: |
          npm install && npx tsc && node ./app/index.js
      - name: Publish Result
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
          add: '["./result"]'
          default_author: github_actions
          fetch: false
          tag_push: "--force"
          message: "Update Subscriptions"
